/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

import javax.swing.*;
import java.awt.event.ActionEvent;

public class OpsiMenu extends javax.swing.JFrame implements OperasiPerbankan {
    int saldo;
    Barometer barometer; // Menambahkan barometer

    public OpsiMenu() {
        initComponents();
        barometer = new Barometer(); // Inisialisasi barometer
        jPanel1.add(barometer); // Menambahkan barometer ke panel
    }

    public OpsiMenu(int saldo) {
        this.saldo = saldo;
        initComponents();
        barometer = new Barometer(); // Inisialisasi barometer
        jPanel1.add(barometer); // Menambahkan barometer ke panel
        perbaruiTampilan(); // Memperbarui tampilan awal
    }

    @Override
    public void setor(int jumlah) {
        saldo += jumlah;
        perbaruiTampilan();
    }

    @Override
    public void tarik(int jumlah) {
        if (saldo < jumlah) {
            JOptionPane.showMessageDialog(rootPane, "Maaf saldo Anda kurang.");
        } else {
            saldo -= jumlah;
            perbaruiTampilan();
        }
    }

    @Override
    public void transfer(int jumlah, String penerima) {
        if (saldo < jumlah) {
            JOptionPane.showMessageDialog(rootPane, "Maaf saldo Anda kurang.");
        } else {
            saldo -= jumlah;
            JOptionPane.showMessageDialog(rootPane, "Berhasil transfer kepada " + penerima + " sebesar " + jumlah);
            perbaruiTampilan();
        }
    }

    @Override
    public int cekSaldo() {
        return saldo;
    }

    private void perbaruiTampilan() {
        String jawaban = String.format("Saldo Anda saat ini adalah: %,.2f", (double) saldo);
        TXTTAMPILAN.setText(jawaban);
        JOptionPane.showMessageDialog(rootPane, jawaban);
        barometer.setSaldo(saldo); // Memperbarui barometer
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTNSTORTUNAI = new javax.swing.JButton();
        BTNLIHATSALDO = new javax.swing.JButton();
        BTNTRANFER = new javax.swing.JButton();
        BTNTARIKTUNAI = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        batencancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTTAMPILAN = new javax.swing.JTextField();
        BTNCLEAR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BTNSTORTUNAI.setText("SETOR TUNAI");
        BTNSTORTUNAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSTORTUNAIActionPerformed(evt);
            }
        });

        BTNLIHATSALDO.setText("LIHAT SALDO");
        BTNLIHATSALDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLIHATSALDOActionPerformed(evt);
            }
        });

        BTNTRANFER.setText("TRANFER");
        BTNTRANFER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTRANFERActionPerformed(evt);
            }
        });

        BTNTARIKTUNAI.setText("TARIK TUNAI");
        BTNTARIKTUNAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTARIKTUNAIActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/macintosh/Pictures/LIGO - logo/folder tanpa judul/Desain tanpa judul 2/8.png")); // NOI18N

        batencancel.setText("CANCEL");
        batencancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batencancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("MENU");

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/macintosh/Pictures/LIGO - logo/folder tanpa judul/Desain tanpa judul 3/9.png")); // NOI18N

        TXTTAMPILAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTAMPILANActionPerformed(evt);
            }
        });

        BTNCLEAR.setText("CLEAR");
        BTNCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCLEARActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("TAMPILAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNCLEAR)
                .addGap(18, 18, 18)
                .addComponent(batencancel)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TXTTAMPILAN, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(104, 104, 104)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNLIHATSALDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNTRANFER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNTARIKTUNAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNSTORTUNAI, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTTAMPILAN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNLIHATSALDO)
                    .addComponent(BTNTARIKTUNAI))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNTRANFER)
                    .addComponent(BTNSTORTUNAI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batencancel)
                            .addComponent(BTNCLEAR))
                        .addGap(39, 39, 39))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/macintosh/Pictures/LIGO - logo/folder tanpa judul/Desain tanpa judul 4/1.png")); // NOI18N
        jLabel4.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("SELAMAT ");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("DATANG DI BANK BRI");

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/macintosh/Pictures/LIGO - logo/folder tanpa judul/Desain tanpa judul 3/9.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)))
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSTORTUNAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSTORTUNAIActionPerformed
int masukan = Integer.parseInt(JOptionPane.showInputDialog("Masukkan jumlah setor tunai: "));
        setor(masukan);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNSTORTUNAIActionPerformed

    private void BTNLIHATSALDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLIHATSALDOActionPerformed
 cekSaldo();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNLIHATSALDOActionPerformed

    private void BTNTRANFERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTRANFERActionPerformed
String namaPenerima = JOptionPane.showInputDialog("Silahkan masukkan nama penerima: ");
        int jumlahTransfer = Integer.parseInt(JOptionPane.showInputDialog("Masukkan nominal transfer: "));
       transfer(jumlahTransfer, namaPenerima);
    }//GEN-LAST:event_BTNTRANFERActionPerformed

    private void BTNTARIKTUNAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTARIKTUNAIActionPerformed
int jumlahTarik = Integer.parseInt(JOptionPane.showInputDialog("Masukkan jumlah tarik tunai: "));
        tarik(jumlahTarik);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNTARIKTUNAIActionPerformed

    private void TXTTAMPILANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTAMPILANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTAMPILANActionPerformed

    private void batencancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batencancelActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_batencancelActionPerformed

    private void BTNCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCLEARActionPerformed
TXTTAMPILAN.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        java.awt.EventQueue.invokeLater(() -> {
            new OpsiMenu(10000).setVisible(true); // Inisialisasi dengan saldo awal 10.000
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCLEAR;
    private javax.swing.JButton BTNLIHATSALDO;
    private javax.swing.JButton BTNSTORTUNAI;
    private javax.swing.JButton BTNTARIKTUNAI;
    private javax.swing.JButton BTNTRANFER;
    private javax.swing.JTextField TXTTAMPILAN;
    private javax.swing.JButton batencancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
